
FROM python:latest

WORKDIR /flask_app

COPY . .
RUN apt-get update -y && apt-get upgrade -y && apt-get install curl -y
RUN pip install -r requirements.txt
RUN pip freeze dotenv

ENV PATH="/root/.local/bin:$PATH"

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    POETRY_HOME='/root/.local'

RUN poetry install --no-root
EXPOSE 5000:5000 


CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]



